version: '3.6'
services:
  node:
    container_name: project_api_node
    build: .
    working_dir: /home/node/app
    ports:
      - '3000:3000'
    volumes:
      - './src:/home/node/app'
    links:
      - mongo
    networks:
      - my-network
  mongo:
    container_name: project_api_mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
